{% set name = "perl-module-runtime" %}
{% set version = "0.018" %}
{% set sha256 = "0bf77ef68e53721914ff554eada20973596310b4e2cf1401fc958601807de577" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  url: https://cpan.metacpan.org/authors/id/H/HA/HAARG/Module-Runtime-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 2
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  host:
    - perl
    - perl-module-build
  run:
    - perl

test:
  imports:
    - Module::Runtime

about:
  home: http://metacpan.org/pod/Module-Runtime
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file: LICENSE
  summary: 'runtime module handling'

extra:
  recipe-maintainers:
    - xileF1337
    - conda-forge/perl-packagers
    - martin-g
